Fix not passing format string to `printf`

diff --git a/start-or-focus b/start-or-focus
--- a/start-or-focus
+++ b/start-or-focus
@@ -1,8 +1,8 @@
 #! /bin/sh
 
 case $1 in
-  (--version | -V | -v) exec printf "\
-Start or Focus 1.0.0
+  (--version | -V | -v) exec printf "%s" "\
+Start or Focus 1.0.1
 
 Copyright © 2017 Henrik Franciscus Leppä
 
@@ -11,7 +11,7 @@ MIT License <https://opensource.org/licenses/MIT>. There is NO WARRANTY, to the
 extent permitted by law.
 
 " ;;
-  (--help | -H | -h | -\?) exec printf "\
+  (--help | -H | -h | -\?) exec printf "%s" "\
 Starts an application, or if it is already running, gives it focus.
 
 Usage: start-or-focus <name> [ <process> [ <command> ] ]
@@ -49,21 +49,21 @@ ex_oserr=71
 for i do
   case $i in
     (-*)
-      printf "Invalid option: '$i'\n\n" >& 2
-      printf "Use '--help' option to see all valid options.\n\n" >& 2
+      printf "%s\n\n" "Invalid option: '$i'" >& 2
+      printf "%s\n\n" "Use '--help' option to see all valid options." >& 2
       exit $ex_usage
       ;;
   esac
 done
 
 if [ ! "$(command -v pidof)" ]; then
-  printf "Command 'pidof' was not found. Install it and try again.\n" >& 2
+  printf "%s\n" "Command 'pidof' was not found. Install it and try again." >& 2
   exit $ex_oserr
 fi
 
 
 if [ ! "$(command -v wmctrl)" ]; then
-  printf "Command 'wmctrl' was not found. Install it and try again.\n" >& 2
+  printf "%s\n" "Command 'wmctrl' was not found. Install it and try again." >& 2
   exit $ex_oserr
 fi
 
@@ -74,14 +74,14 @@ case $# in
   (1) application_process=$1 ; application_command=$1 ;;
   (2) application_process=$2 ; application_command=$2 ;;
   (3) application_process=$2 ; application_command=$3 ;;
-  (*) printf "$argument_number_error" >& 2 ; exit $ex_usage ;;
+  (*) printf "%s" "$argument_number_error" >& 2 ; exit $ex_usage ;;
 esac
 
 
 if [ "$(pidof $application_process)" ]; then
-  printf "$application_name is already running; giving it focus.\n"
+  printf "%s\n" "$application_name is already running; giving it focus."
   wmctrl -a "$application_name"
 else
-  printf "$application_name is not running; starting it.\n"
+  printf "%s\n" "$application_name is not running; starting it."
   $application_command &
 fi
