Add double dash (`--`) before positional arguments
Positional arguments that start with dashes are no longer read as flags.

diff --git a/start-or-focus b/start-or-focus
--- a/start-or-focus
+++ b/start-or-focus
@@ -2,9 +2,13 @@
 
 set -e
 
+# [See sysexits.h](https://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3)
+ex_usage=64
+ex_oserr=71
+
 case $1 in
   (--version | -V | -v) exec printf "%s" "\
-Start or Focus 1.1.0
+Start or Focus 2.0.0
 
 Copyright © 2017--2018 Henrik Franciscus Leppä
 
@@ -16,7 +20,7 @@ extent permitted by law.
   (--help | -H | -h | -\?) exec printf "%s" "\
 Starts an application, or if it is already running, gives it focus.
 
-Usage: start-or-focus <name> [ <process> [ <command> ] ]
+Usage: start-or-focus -- <name> [ <process> [ <command> ] ]
    or: start-or-focus ( --help | --version | -H | -h | -? | -V | -v )
 
 Options:
@@ -36,27 +40,16 @@ Options:
 Note: May accidentally focus the wrong window if <name> is found in its title.
 
 " ;;
+  (--)
+    shift
+  ;;
+  (*)
+    printf "%s\\n\\n" "Invalid option: '$1'" >& 2
+    printf "%s\\n\\n" "Use '--help' option to see all valid options." >& 2
+    exit $ex_usage
+  ;;
 esac
 
-
-argument_number_error="\
-Incorrect number of arguments, should be 1, 2 or 3, instead was: $#
-"
-
-# [See sysexits.h](https://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3)
-ex_usage=64
-ex_oserr=71
-
-
-for i do
-  case $i in
-    (-*)
-      printf "%s\\n\\n" "Invalid option: '$i'" >& 2
-      printf "%s\\n\\n" "Use '--help' option to see all valid options." >& 2
-      exit $ex_usage
-      ;;
-  esac
-done
 
 if [ ! "$(command -v pidof)" ]; then
   printf "%s\\n" "Command 'pidof' was not found. Install it and try again." >& 2
@@ -71,14 +64,19 @@ if [ ! "$(command -v wmctrl)" ]; then
 fi
 
 
-application_name=$1
+argument_number_error="\
+Incorrect number of positional arguments, should be 1, 2 or 3, instead was: $#
+"
 
-case $# in
-  (1) application_process=$1 ; application_command=$1 ;;
-  (2) application_process=$2 ; application_command=$2 ;;
-  (3) application_process=$2 ; application_command=$3 ;;
-  (*) printf "%s" "$argument_number_error" >& 2 ; exit $ex_usage ;;
-esac
+if [ $# -lt 1 ] || [ 3 -lt $# ]; then
+  printf "%s" "$argument_number_error" >& 2
+  exit $ex_usage
+fi
+
+
+application_name=$1
+application_process=${2:-$application_name}
+application_command=${3:-$application_process}
 
 
 if [ "$(pidof "$application_process")" ]; then
